### ISSUE TITLE
This button crashes the client

### ISSUE THREAD

**Issue by krumble1** [BBoldt/partlycloudy#5]
Clicking this button causes the client to exit.

![image](https://github.com/BBoldt/partlycloudy/assets/12228024/311dbc4e-0b29-47f0-8481-7e3961ec360a)

[\(Crash log\)](https://github.com/user-attachments/files/16117304/crash-2024-07-06_15.34.38-client.txt)

**Comment by BBoldt** [comment]
https://github.com/blackd/Inventory-Profiles/issues/420

**Comment by BBoldt** [comment]
fixed in new version
